<?php
$parameters = array(
	'cache_path' => '%kernel.root_dir%/cache',
	'log_path' => '%kernel.root_dir%/logs',
	'site_url' => 'http://localhost:8888/EDENS%20Mautic',
	'install_source' => 'Mautic',
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => 'mautic_',
	'db_port' => '8889',
	'db_name' => 'Mautic',
	'db_user' => 'root',
	'db_password' => 'root',
	'db_path' => null,
	'mailer_from_name' => 'Kyle Sobus',
	'mailer_from_email' => 'ksobus@edens.com',
	'mailer_transport' => 'mautic.transport.amazon',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => 'kylesobus@live.com',
	'mailer_password' => 'Carly407',
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => 'd6723f9fc3adcf2bb272e8a30a20b6a0808249825defdadecaa0b39b8be3ec28',
);
